/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Recordings */
        get: operations["list_recordings_api_recordings_get"];
        put?: never;
        /** Upload Recording */
        post: operations["upload_recording_api_recordings_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Recording */
        get: operations["get_recording_api_recordings__recording_id__get"];
        put?: never;
        post?: never;
        /** Delete Recording */
        delete: operations["delete_recording_api_recordings__recording_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Audio
         * @description The 16 kHz copy once prepared (its timestamps are the reference), else the original upload.
         */
        get: operations["get_audio_api_recordings__recording_id__audio_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_api_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job Events
         * @description Server-Sent Events: a `progress` event whenever the job changes, then `end`.
         */
        get: operations["job_events_api_jobs__job_id__events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{job_id}/retry": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry Job */
        post: operations["retry_job_api_jobs__job_id__retry_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transcript */
        get: operations["get_transcript_api_recordings__recording_id__transcript_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/speakers/{speaker_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Rename Speaker */
        patch: operations["rename_speaker_api_recordings__recording_id__speakers__speaker_id__patch"];
        trace?: never;
    };
    "/api/utterances/{utterance_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Edit Utterance */
        patch: operations["edit_utterance_api_utterances__utterance_id__patch"];
        trace?: never;
    };
    "/api/recordings/{recording_id}/analytics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Analytics */
        get: operations["get_analytics_api_recordings__recording_id__analytics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export Recording */
        get: operations["export_recording_api_recordings__recording_id__export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/insights": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Insights */
        get: operations["get_insights_api_recordings__recording_id__insights_get"];
        put?: never;
        /** Generate Insights */
        post: operations["generate_insights_api_recordings__recording_id__insights_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/recordings/{recording_id}/ask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ask History */
        get: operations["ask_history_api_recordings__recording_id__ask_get"];
        put?: never;
        /** Ask Question */
        post: operations["ask_question_api_recordings__recording_id__ask_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Task */
            task: string;
            /** Owner Speaker Id */
            owner_speaker_id?: string | null;
            /** Due Text */
            due_text?: string | null;
            /** Evidence */
            evidence?: components["schemas"]["Citation"][];
            /**
             * Status
             * @default verified
             * @enum {string}
             */
            status: "verified" | "unverified";
        };
        /** AnalyticsOut */
        AnalyticsOut: {
            /** Duration S */
            duration_s: number;
            /** Silence Ratio */
            silence_ratio: number;
            /** Speakers */
            speakers: components["schemas"]["SpeakerStatsOut"][];
        };
        /** AskCitationOut */
        AskCitationOut: {
            /** Uid */
            uid: string;
            /**
             * Utterance Id
             * Format: uuid
             */
            utterance_id: string;
            /** Speaker Id */
            speaker_id: string | null;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Quote */
            quote: string;
        };
        /** AskIn */
        AskIn: {
            /** Question */
            question: string;
        };
        /** AskTurnOut */
        AskTurnOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Question */
            question: string;
            /** Answer */
            answer: string;
            /** Abstained */
            abstained: boolean;
            /** Abstain Reason */
            abstain_reason: ("model_declined" | "no_valid_citation" | "unsupported_answer") | null;
            /** Citations */
            citations: components["schemas"]["AskCitationOut"][];
            /** Model */
            model: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** Body_upload_recording_api_recordings_post */
        Body_upload_recording_api_recordings_post: {
            /** File */
            file: string;
            /** Title */
            title?: string | null;
            /**
             * Type
             * @default meeting
             */
            type: string;
            /** Language */
            language?: string | null;
            /** Min Speakers */
            min_speakers?: number | null;
            /** Max Speakers */
            max_speakers?: number | null;
        };
        /** Chapter */
        Chapter: {
            /** Title */
            title: string;
            /** Start Uid */
            start_uid: string;
            /** End Uid */
            end_uid: string;
        };
        /** Citation */
        Citation: {
            /** Utterance Id */
            utterance_id: string;
        };
        /** Decision */
        Decision: {
            /** Text */
            text: string;
            /** Evidence */
            evidence?: components["schemas"]["Citation"][];
            /**
             * Status
             * @default verified
             * @enum {string}
             */
            status: "verified" | "unverified";
        };
        /** FeaturesOut */
        FeaturesOut: {
            /** Insights */
            insights: boolean;
            /** Ask */
            ask: boolean;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthOut */
        HealthOut: {
            /**
             * Status
             * @constant
             */
            status: "ok";
            features: components["schemas"]["FeaturesOut"];
        };
        /** Insights */
        Insights: {
            summary?: components["schemas"]["SummaryPoint"] | null;
            /**
             * Key Points
             * @default []
             */
            key_points: components["schemas"]["SummaryPoint"][];
            /**
             * Decisions
             * @default []
             */
            decisions: components["schemas"]["Decision"][];
            /**
             * Action Items
             * @default []
             */
            action_items: components["schemas"]["ActionItem"][];
            /**
             * Chapters
             * @default []
             */
            chapters: components["schemas"]["Chapter"][];
            /**
             * Open Questions
             * @default []
             */
            open_questions: components["schemas"]["OpenQuestion"][];
        };
        /**
         * InsightsOut
         * @description `data` is the latest finished run, even while a newer run is going or has failed.
         */
        InsightsOut: {
            /**
             * Status
             * @enum {string}
             */
            status: "none" | "running" | "done" | "failed";
            /** Error */
            error?: string | null;
            /** Model */
            model?: string | null;
            /** Version */
            version?: number | null;
            /** Created At */
            created_at?: string | null;
            /**
             * Stale
             * @default false
             */
            stale: boolean;
            data?: components["schemas"]["Insights"] | null;
            /** Validation */
            validation?: {
                [key: string]: unknown;
            } | null;
        };
        /** JobOut */
        JobOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "done" | "failed";
            /** Current Stage */
            current_stage: string | null;
            /** Progress */
            progress: number;
            /** Attempts */
            attempts: number;
            /** Error */
            error: string | null;
            /** Stages */
            stages: components["schemas"]["StageOut"][];
        };
        /** OpenQuestion */
        OpenQuestion: {
            /** Text */
            text: string;
            /** Evidence */
            evidence?: components["schemas"]["Citation"][];
            /**
             * Status
             * @default verified
             * @enum {string}
             */
            status: "verified" | "unverified";
        };
        /** RecordingOut */
        RecordingOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Type */
            type: string;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "processing" | "ready" | "failed";
            /** Duration S */
            duration_s: number | null;
            /** Language */
            language: string | null;
            /** Source Filename */
            source_filename: string;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            job?: components["schemas"]["JobOut"] | null;
        };
        /** SpeakerOut */
        SpeakerOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Label */
            label: string;
            /** Name */
            name: string;
            /** Display Name */
            display_name: string | null;
            /** Color */
            color: string | null;
            /** Talk Time S */
            talk_time_s: number;
        };
        /** SpeakerPatch */
        SpeakerPatch: {
            /** Display Name */
            display_name?: string | null;
        };
        /** SpeakerStatsOut */
        SpeakerStatsOut: {
            /**
             * Speaker Id
             * Format: uuid
             */
            speaker_id: string;
            /** Name */
            name: string;
            /** Color */
            color: string | null;
            /** Talk Time S */
            talk_time_s: number;
            /** Talk Share */
            talk_share: number;
            /** Turns */
            turns: number;
            /** Words */
            words: number;
            /** Words Per Minute */
            words_per_minute: number;
            /** Longest Monologue S */
            longest_monologue_s: number;
            /** Interruptions Made */
            interruptions_made: number;
        };
        /** StageOut */
        StageOut: {
            /** Name */
            name: string;
            /** Label */
            label: string;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "done" | "skipped" | "failed";
            /** Seconds */
            seconds?: number | null;
        };
        /** SummaryPoint */
        SummaryPoint: {
            /** Text */
            text: string;
            /** Evidence */
            evidence?: components["schemas"]["Citation"][];
            /**
             * Status
             * @default verified
             * @enum {string}
             */
            status: "verified" | "unverified";
        };
        /** TranscriptOut */
        TranscriptOut: {
            /**
             * Recording Id
             * Format: uuid
             */
            recording_id: string;
            /** Language */
            language: string | null;
            /** Duration S */
            duration_s: number | null;
            /** Speakers */
            speakers: components["schemas"]["SpeakerOut"][];
            /** Utterances */
            utterances: components["schemas"]["UtteranceOut"][];
        };
        /** UtteranceOut */
        UtteranceOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Idx */
            idx: number;
            /** Uid */
            uid: string;
            /** Speaker Id */
            speaker_id: string | null;
            /** Start S */
            start_s: number;
            /** End S */
            end_s: number;
            /** Text */
            text: string;
            /** Words */
            words: components["schemas"]["WordOut"][];
            /** Has Overlap */
            has_overlap: boolean;
            /** Edited */
            edited: boolean;
        };
        /** UtterancePatch */
        UtterancePatch: {
            /** Text */
            text: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** WordOut */
        WordOut: {
            /** Text */
            text: string;
            /** Start */
            start: number;
            /** End */
            end: number;
            /** Probability */
            probability?: number | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthOut"];
                };
            };
        };
    };
    list_recordings_api_recordings_get: {
        parameters: {
            query?: {
                q?: string | null;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_recording_api_recordings_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_recording_api_recordings_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_recording_api_recordings__recording_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_recording_api_recordings__recording_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_audio_api_recordings__recording_id__audio_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_api_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    job_events_api_jobs__job_id__events_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    retry_job_api_jobs__job_id__retry_post: {
        parameters: {
            query?: {
                from_stage?: string | null;
            };
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transcript_api_recordings__recording_id__transcript_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TranscriptOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_speaker_api_recordings__recording_id__speakers__speaker_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
                speaker_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SpeakerPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SpeakerOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    edit_utterance_api_utterances__utterance_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                utterance_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UtterancePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UtteranceOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_analytics_api_recordings__recording_id__analytics_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AnalyticsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_recording_api_recordings__recording_id__export_get: {
        parameters: {
            query: {
                format: string;
            };
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_insights_api_recordings__recording_id__insights_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_insights_api_recordings__recording_id__insights_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InsightsOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_history_api_recordings__recording_id__ask_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskTurnOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ask_question_api_recordings__recording_id__ask_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                recording_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AskIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AskTurnOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
